import React, { useState } from "react";
import { useRouter } from "next/router";
import Head from 'next/head'
import Link from "next/link";


const LoginPage = () => {
  const router = useRouter();
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const { myParam } = router.query;

  

  return (<>
    <Head>
        <title>SXDC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>

      <main className={styles.main}>
          <div className="styles.description">
             <p>Welcome ... {myParam} </p>  
          </div>
            <div className={styles.center}>
           Welcome to Home page 
            </div>
        </main>
  
  
  
  
  
  
  </>);
};

export default home;
