import React, { useState } from "react";
import { useRouter } from "next/router";
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from "next/link";


const HomePage = () => {
  const router = useRouter();
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const { ref } = router.query;

  

  return (<>
    <Head>
        <title>SXDC-home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>

      <main className={styles.main}>
          <div className="styles.description">
             <p>Welcome ... {ref} </p>  
          </div>
            <div className={styles.center}>
              <p><input type='button' value="Upload Monthly Returns" style="height:5em; width:50em"/></p>
              <p>Upload your Monthly returns</p>
            </div>
            <div className={styles.center}>
              <p>Upload your Monthly returns</p>
              <p><input type='button' value="Upload Monthly Returns" style="height:5em; width:50em"/></p>
            </div>
        </main>
  
  
  
  
  
  
  </>);
};

export default HomePage;
