import React, { useState } from "react"
import { useRouter } from "next/router"
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from "next/link";


const LoginPage = () => {
  const router = useRouter();
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  //const { ref } = router.query;

  const handleLogin = async (event) => {
    event.preventDefault();
    // Do your login logic here, such as making an API call to authenticate the user
    // If login is successful, redirect to home page
    router.push("/validate");
    onSubmit={handleLogin}
  };
  

    
  return (<>
    <Head>
        <title>SXDC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>

      <main className={styles.main}>
       
          <div className={styles.center}>
            <div classname={styles.card}>
              <span>New User Sign-up</span>
              <span>Existing Users Login</span>
            </div>
                <form >
                <div classname={styles.card}>
                  <select>
                    <option>Agra</option>
                    <option>Amristsar</option>
                    <option>Agarthala</option>
                    <option>Azamgarh</option>
                    <option>Bangarpeth</option>
                    <option>Bengaluru</option>
                    <option>Bethul</option>
                    <option>Betia</option>
                  </select>
                </div>
                
                <label>
                Username:
                <input type="text" value={username} onChange={(e) => setUsername(e.target.value)} />
                </label>
                <label>
                Password:
                <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} />
                </label>
                <button type="submit">Login</button>
                </form>    
          </div>
           
      
        
            
      </main>
  
  
  
  
  
  
  </>);
};

export default LoginPage;
