import React, { useState } from "react";
import { useRouter } from "next/router";
import Link from "next/link";


const LoginPage = () => {
  const router = useRouter();
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const { myParam } = router.query;

  const handleLogin = async (event) => {
    event.preventDefault();
    // Do your login logic here, such as making an API call to authenticate the user
    // If login is successful, redirect to home page
    router.push("/home");
  };

  return (<>
    <Head>
        <title>SXDC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>

      <main className={styles.main}>
          <div className="styles.description">
             <p>Welcome ... {myParam} !</p>  
          </div>
            <div className={styles.center}>
                <form onSubmit={handleLogin}>
                <label>
                Username:
                <input type="text" value={username} onChange={(e) => setUsername(e.target.value)} />
                </label>
                <label>
                Password:
                <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} />
                </label>
                <button type="submit">Login</button>
                </form>    
            </div>
        </main>
  
  
  
  
  
  
  </>);
};

export default LoginPage;
